[package]
name = "chesseng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
ndarray = "0.15.6"
rand = "0.8.5"
bincode = "1.3"

[dev-dependencies]
criterion = "0.5.1"

#[[bench]]
#name = "movegen_bench"
#harness = false

[[bench]]
name = "full_gen_bench"
harness = false
